version: '2.1'
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.3
jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          registry-url: us-central1-docker.pkg.dev
      - gcp-gcr/build-image:
          image: api
          registry-url: us-central1-docker.pkg.dev/docker-repo
      - gcp-gcr/push-image:
          image: api
          registry-url: us-central1-docker.pkg.dev/docker-repo
workflows:
  commit:
    jobs:
      - build-and-push
