version: '2.1'
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.3
jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      # - gcp-gcr/gcr-auth:
      #     gcloud-service-key: GCLOUD_SERVICE_KEY
      - gcp-gcr/build-image:
          image: api
          no_output_timeout: 20m
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: orb-test
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push
