version: '2.1'
orbs:
  gcp-gcr: circleci/gcp-gcr@0.16.3
jobs:
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          registry-url: us-central1-docker.pkg.dev
      - gcp-gcr/build-image:
          image: api
          registry-url: us-central1-docker.pkg.dev/investmentbot-425621/docker-repo
      - gcp-gcr/push-image:
          image: api
          registry-url: us-central1-docker.pkg.dev/investmentbot-425621/docker-repo
  deploy-cloud-run:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy backend --project=investmentbot-425621 --image=us-central1-docker.pkg.dev/investmentbot-425621/docker-repo/investmentbot-425621/api:latest --platform=managed --region=us-central1
  jcml-unit-test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run JCML Unit Tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests

workflows:
  commit:
    jobs:
      - jcml-unit-test
      - build-and-push:
          requires:
            - jcml-unit-test
          filters:
            branches:
              only: main
      - deploy-cloud-run:
          requires:
            - build-and-push
          filters:
            branches:
              only: main